services:
# これから起動するコンテナ一覧を書く宣言
  web:
  # コンテナの名前
  # このコンテナはDockerfileでPythonとPoetryが入ったコンテナを作り、
  # docker-compose.ymlでそのコンテナを起動し
  # Poetry管理のDjangoプロジェクトを実行している。

    build: .
    # このディレクトリ(.)にあるDockerfileを使ってコンテナを作る
    command: poetry run python manage.py runserver 0.0.0.0:8000
    # 起動コマンド
    ports:
      - "8000:8000"
    # ローカルPC:8000 → コンテナ:8000
    volumes:
      - .:/app
    # ローカルのプロジェクトフォルダ　.(Todo_app)を
    # コンテナ内の/appにバインドマウントしている
    # ローカルの変更が即コンテナに反映される
    working_dir: /app
    # コマンドの実行場所を/appに指定し、/app内にあるDjangoプロジェクトのコード(manage.py)
    # を使って、 Dockerがその場所でサーバー起動コマンドを実行している
    # (poetry run python manage.py runserver)
    # コンテナの中にはLinuxファイルシステム(OSっぽく見えるもの)がある
    # /appはそのLinuxファイルシステム内のディレクトリの一つ
    

    # バインドマウントとは
    # DockerをインストールしたPCのドキュメントやデスクトップなどDocker Engineの管理していない
    # ファイルシステム上の既に存在するディレクトリやファイルをコンテナ内のパスに直接マウントする仕組み
    # ディレクトリだけではなく、ファイル単位でもマウント可能
    # ローカルで編集した内容が即座にコンテナに反映されるため
    # 開発中に頻繁に触るソースコードなどに向いている

    
