services:
# これから起動するコンテナ一覧を書く宣言
  web:
  # コンテナの名前
  # このコンテナはDockerfileでPythonとPoetryが入ったコンテナを作り、
  # docker-compose.ymlでそのコンテナを起動し
  # Poetry管理のDjangoプロジェクトを実行している。

    build: .
    # このディレクトリ(.)にあるDockerfileを使ってコンテナを作る

    env_file:
      - .env
    # environment:
    #   DJANGO_DEBUG: "True"
    # env.ファイルの中身をタイポしていたため、最初のコンテナ起動時に
    # DJANGO_DEBUG が os.environ に読み込まれなかった。
    # compose exec web env | grep DJANGO で確認した際に値が存在しなかったため、
    # .env が正しく読まれているかを切り分ける目的で一時的に environment を使用した。
    #
    # 環境変数はコンテナ起動時に os.environ に読み込まれるため、
    # 正しい .env を用いた状態でコンテナを作り直した後は
    # environment を削除しても env_file 経由の設定で正常に動作する。
    #
    # ※ コンテナを削除（docker compose down）した場合は、
    #   起動時に再度 env_file から読み込まれる。

    
    # .env
    #   ↓
    # Docker（env_file / environment）
    #   ↓
    # 箱（os.environ）
    #   ↓
    # Django（settings.py）



    # 今までsetting.pyに直書きしていたSECRET_KEYを.envファイルに書いたため必要
    # Django が参照する環境変数（SECRET_KEY / DEBUG など）を読み込む



    # 新起動コマンド(Gunicorn)
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2
    # poetry run ← poetryの仮想環境で
    # gunicorn ← Gunicornを使って
    # config.wsgi:application ← Djangoの起動入口
    # --bind 0.0.0.0:8000 ← このポートで待ち受け
    # --workers 2 → リクエストを並列処理するworkerプロセス数(CPUを使う主体の数)


    # Gunicornの導入により不要になったためコメントアウト
    # 本番環境では Django の開発用サーバ（runserver）は使用せず、
    # WSGIサーバである Gunicorn を利用する。
    # command: poetry run python manage.py runserver 0.0.0.0:8000
    # 起動コマンド

    # これはnginxを入れたことで不要になったためコメントアウト
    # レスポンスの入り口をNginxのみにするため
    # ports:
    #   - "8000:8000"
    # # ローカルPC:8000 → コンテナ:8000


    volumes:
      - .:/app
    # ローカルのプロジェクトフォルダ　.(Todo_app)を
    # コンテナ内の/appにバインドマウントしている
    # ローカルの変更が即コンテナに反映される

    working_dir: /app
    # コマンドの実行場所を/appに指定し、/app内にあるDjangoプロジェクトのコード(manage.py)
    # を使って、 Dockerがその場所でサーバー起動コマンドを実行している
    # (poetry run python manage.py runserver)
    # コンテナの中にはLinuxファイルシステム(OSっぽく見えるもの)がある
    # /appはそのLinuxファイルシステム内のディレクトリの一つ

    expose:
      - "8000"
    # nginx → web:8000 → Django
    # Dockerネットワーク内だけで有効
    # nginxリクエスト専用

    depends_on:
      - db
    # webコンテナ起動前に、MySQL(db)コンテナを先に起動させるため
    # Django起動時にDBコンテナが未起動で接続エラーになるのを防ぐ目的
    

  nginx:
  # サービス名
    image: nginx:1.25
    # Docker Hubの公式イメージを使うと言う意味
    ports:
      - "80:80"
      # ローカルPCの80番 → nginxコンテナの80番
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # nginxコンテナ内で設定ファイルとして読み込まれる
      # /etc/nginx/conf.d/default.confに
      # ローカルの./nginx/default.confをバインドマウントしている
      - ./staticfiles:/app/staticfiles:ro
      # ホスト側の./staticfilesをnginxコンテナ内のapp/staticfilesに
      # バインドマウントしている
      # :ro　→ 読み取り専用(nginx新たにstaticは作らず、配信のみを行うため)
    depends_on:
      - web
    # Gunicorn(web)起動後にnginxを起動するため


  db:
    image: mysql:8.0
    # MySQL8.0の公式Dockerイメージを指定
    container_name: mysql
    # 起動するコンテナの名前をmysqlに固定する
    # なくても動くが、ログを見る際やコマンドを叩く際に名前を固定することで楽になる
    environment:
      # コンテナの中に渡す環境変数をここから書く宣言
      MYSQL_DATABASE: todo_db
      # 初回起動時にtodo_dbというDBを自動作成する
      MYSQL_USER: todo_user
      # 初回起動時にtodo_userという一般ユーザーを作る
      MYSQL_PASSWORD: todo_pass
      # 一般ユーザー(todo_user)のパスワード
      MYSQL_ROOT_PASSWORD: rootpass
      # MuSQLの管理者ユーザー(root)のパスワード
    volumes:
      - mysql_data:/var/lib/mysql
      # mysql_data → 名前付きボリューム
      # /var/lib/mysql　→ コンテナにボリュームマウントするためのマウント先(コンテナの中)
      #　つまり名前付きボリューム(mysql_data)をMySQLのデータディレクトリにマウントしている 

    command: --default-authentication-plugin=mysql_native_password
    # MySQL8.0のデフォルト認証方式による、Django(mysqlclient)との
    # 接続エラーを避けるために認証方式を指定している
    # 今回は認証エラーを防ぐ目的で事前に指定しているが
    # 本番環境や使用するクライアントの対応状況によって不要となる場合もある

volumes:
  mysql_data:
  # mysql_dataという名前付きボリュームを作ると宣言している
  # これがあることでボリュームマウントが成立する。



# ボリュームマウントとは
# ボリュームマウントはDocker Enginが管理している領域内にボリュームを作成し、
# ディスクとしてコンテナにマウントする
# 滅多に触らないが、消してはいけないファイルなどに使用する


# バインドマウントとは
# DockerをインストールしたPCのドキュメントやデスクトップなどDocker Engineの管理していない
# ファイルシステム上の既に存在するディレクトリやファイルをコンテナ内のパスに直接マウントする仕組み  
# ディレクトリだけではなく、ファイル単位でもマウント可能
# ローカルで編集した内容が即座にコンテナに反映されるため
# 開発中に頻繁に触るソースコードなどに向いている

#　Dockerの消しては作る性質からコンテナ内のデータは消えてしまうため外にデータを残しておく必要がある 
    
# コンテナ起動順
# db → web → nginx

# 構成
# ブラウザ →(80番) Nginx　→(8000番) Gunicorn → Django → MySQL
