# Generated by Django 4.2 on 2025-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="詳細"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="締切日"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="完了"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
