# Generated by Django 4.2 on 2025-12-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_tag_todo_delete_todos"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="todos", to="todos.tag", verbose_name="タグ"
            ),
        ),
    ]
