# Generated by Django 4.2 on 2025-12-27 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todos", "0003_todo_tags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("user", "name")},
        ),
    ]
