"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
# EC2でアプリを立ち上げるため、コメントアウト(Djangoデフォルト)
# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-fwd=#f-8uj!cj*voa5v7z*sap6w)58depv%s-5p$m$j%ctwl5j"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
DEBUG = os.environ.get("DJANGO_DEBUG") == "True"

ALLOWED_HOSTS = [
    "35.74.232.169",
    "ec2-35-74-232-169.ap-northeast-1.compute.amazonaws.com",
]
# 上２行は「.envに書いた値をPython(Django)が読み取るためのコード」
# SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
# os.environ：環境変数の一覧
# get("DJANGO_SECRET_KEY")：その中からDJANGO_SECRET_KEYという名前の値を取ってくる
# DEBUG = os.environ.get("DJANGO_DEBUG") == "True"
# .envでは値が文字列になるため、"True"のときだけDEBUG=Trueになるように比較している
# つまり、環境変数DJANGO_DEBUGの値が文字として"True"だったらDEBUGをTrueにする。
# それ以外はFalseにする。

# .env（文字）
#    ↓
# "True" / "False"
#    ↓ 比較
# True / False（Djangoが欲しい形）


# 35.74.232.169↓
# awsコンソールEC2のインスタンスのパブリックIPv4アドレス
# ec2-35-74-232-169.ap-northeast-1.compute.amazonaws.com↓
# awsコンソールEC2のインスタンスのパブリックIPv4 DNS名
# どちらもAWSが自動で用意する


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "todos.apps.TodosConfig",
    # 自分が作ったアプリ(todos)と紐づけている
    # todosの中のapps.pyの中のclass(TodosConfig)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    # Djangoが使うDB接続設定の集合
    "default": {
        # Djangoが標準で使うDB接続の名前
        "ENGINE": "django.db.backends.mysql",
        # どの種類のDBを使うか
        # Django本体に最初から入っているMySQL用の接続エンジン
        "NAME": "todo_db",
        # 接続するデータベース名
        # ymlファイルのdbコンテナと一致している必要がある
        "USER": "todo_user",
        # MySQLにログインするユーザー名
        # ymlファイルのdbコンテナと一致している必要がある
        "PASSWORD": "todo_pass",
        # そのユーザーのパスワード
        # ymlファイルのdbコンテナと一致している必要がある
        "HOST": "db",
        # DBサーバーの場所
        # dbはサービス名=ホスト名になる
        "PORT": "3306",
        # MySQLが待受しているポート番号
        # デフォルトが3306
        # これはDjango標準のSQLite用設定(デフォルト)
        # 今回はMySQLを使用するため不要
        # "ENGINE": "django.db.backends.sqlite3",
        # "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authenticaiton settings
LOGIN_REDIRECT_URL = "todo_list"
# ログイン成功後にどこにリダイレクトするか
LOGOUT_REDIRECT_URL = "login"
# ログアウト後にどこへ行くか
LOGIN_URL = "login"
# ログインしてない人が「ログイン必須ページ」に来たとき、どこに飛ばすか
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# SECURE_PROXY_SSL_HEADER：Djangoの公式設定項目
# プロキシ(Nginx)経由のリクエストをDjangoが判定する際、
# もし、X-Forwarded-Protoというヘッダーがあり、
# その値がhttpsだった場合、
# このリクエストは本当にhttpsだったと判断しても良い。とDjangoに伝える設定


# Djangoでは認証はアプリ横断の仕組みとして設計されているため、
# ログイン後や未認証時のリダイレクト先は
# プロジェクト全体の設定として settings.py に定義する
# これにより、Viewの責務をシンプルに保ちつつ、変更にも強い構成になる


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ja"
# 初期設定を英語から日本語に変更

TIME_ZONE = "Asia/Tokyo"
# 時間をの日本時間に変更


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# ブラウザがstaticファイルを取りに来る時のURLの入り口
STATIC_URL = "/static/"

# collectstaticの出力先(実態の置き場所)
STATIC_ROOT = BASE_DIR / "staticfiles"
# Djangoが管理するCSS/JSなどのstaticファイルを
# collectstaic実行時に全てここへ集約するためのディレクトリ
# Nginxはこのディレクトリを参照してstaticファイルを配信する

# venvの時はrunserverがstaticを自動で処理してくれていたが、
# Django + Gunicorn + Nginx構成ではDjangoはstaticを配信しないため
# collectstaticとSTATIC_ROOTの設定が必要になる

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
