server {
    listen 80;
    # nginxが８０番で待ち受ける

    # staticファイル配信
    location /static/ {
    # /static/で始まるURL来たら
        alias /app/staticfiles/;
        # /app/staticfiles/(Nginxのコンテナの中)に置いてあるファイルをそのまま返す
    }

    location / {
    # /に来たリクエストを
        proxy_pass http://web:8000;
        # Docker内のwebコンテナの8000番へ転送
        proxy_set_header Host $host;
        # proxy_set_header：NginxがDjangoに転送するとき、HTTPヘッダーをこう設定して渡してね。と言う意味
        # Host：ブラウザが、どのドメインにアクセスしたいかを伝える情報
        # $host：Nginxが受け取ったリクエストのHostをそのまま使う変数
        # 要するにブラウザが指定したHostを、そのままDjangoにも伝える
        proxy_set_header X-Real-IP $remote_addr;
        # $remote_addr:Nginxから見たアクセスしてるPCのIP
        # このIPは認証やログ用途で使用される
        # 要するに、本当のアクセス元IPをDjangoに教える
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # X-Forwarded-For：このリクエストは代理(Nginx)を通ってきたよ。元のIPはこれだよ。と言う履歴
        # $proxy_add_x_forwarded_for：すでにX-Forwarded-Forが付いてたらそれを維持しつつ
        # そこに$remote_addrを追記してくれる便利変数
        # 要するにプロキシを何段通っても元のIPの履歴が残る
        proxy_set_header X-Forwarded-Proto $scheme;
        # ブラウザから受け取ったプロトコルがhttpsだったとしても
        # HTTPSはNginxで終端されるため
        # Nginx → Djangoの通信は通常 http になる
        # そのためブラウザ　→ Nginxが http/httpsのどちらだったかをDjangoに伝える必要がある
        # X-Forwarded-Proto：元のリクエスがhttp / httpsだったかDjangoに伝えるためのヘッダー
        # Prot:プロトコル　http/https
        # $scheme:Nginxが受け取ったリクエストのプロトコルを変数にする
        # http なら http
        # https なら https
        # 要するにhttp/httpsどっちで来たかをDjangoに伝える
        # ブラウザ --https--> Nginx --http--> Django


        
    }
}

# Nginxがいない世界(直アクセス)ブラウザ　→ Django
